Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 CRITICAL nova [req-f37a9f28-6f03-4c8b-81b1-1f620e5d1a1f - - - - -] ContextualVersionConflict: (pbr 1.10.0 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('pbr>=2.0.0'), set(['oslo.i18n', 'oslo.log', 'oslo.context', 'oslo.utils']))
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova Traceback (most recent call last):
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/bin/nova-api", line 10, in <module>
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     sys.exit(main())
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/cmd/api.py", line 59, in main
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     server = service.WSGIService(api, use_ssl=should_use_ssl)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/service.py", line 311, in __init__
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     self.app = self.loader.load_app(name)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/wsgi.py", line 497, in load_app
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return deploy.loadapp("config:%s" % self.config_path, name=name)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return loadobj(APP, uri, name=name, **kw)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return context.create()
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return self.object_type.invoke(self)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 144, in invoke
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     **context.local_conf)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     val = callable(*args, **kw)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/urlmap.py", line 31, in urlmap_factory
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     app = loader.get_app(app_name, global_conf=global_conf)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 350, in get_app
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     name=name, global_conf=global_conf).create()
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return self.object_type.invoke(self)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 203, in invoke
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     app = context.app_context.create()
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return self.object_type.invoke(self)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return fix_call(context.object, context.global_conf, **context.local_conf)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     val = callable(*args, **kw)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/wsgi.py", line 270, in factory
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return cls(**local_config)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/api/metadata/handler.py", line 49, in __init__
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     expiration_time=CONF.api.metadata_cache_expiration)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/cache_utils.py", line 58, in get_client
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     backend='oslo_cache.dict'))
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/cache_utils.py", line 96, in _get_custom_cache_region
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     region.configure(backend, **region_params)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 413, in configure
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     backend_cls = _backend_loader.load(backend)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/dogpile/util/langhelpers.py", line 40, in load
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     return impl.load()
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2301, in load
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     self.require(*args, **kwargs)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     items = working_set.resolve(reqs, env, installer, extras=self.extras)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova     raise VersionConflict(dist, req).with_context(dependent_req)
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova ContextualVersionConflict: (pbr 1.10.0 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('pbr>=2.0.0'), set(['oslo.i18n', 'oslo.log', 'oslo.context', 'oslo.utils']))
Mar 29 18:33:11 altocumulus01 nova-api[1155]: 2017-03-29 18:33:11.433 1155 ERROR nova

